### ISSUE TITLE
Use a single workflow that runs on macOS

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#102]
This is just for discussion - personally I think there are advantages both ways, the main advantage I think to having one workflow is simplicity but having spent a fair bit of time on doing more stuff in CI (such as screenshots and deploying) I think the advantage of simplicity becomes significant.

**Comment by nickmeinhold** [comment]
@Jei @tourdownunder I'd love to get your thoughts 🤔

**Comment by Jei** [comment]
I vote for a single workflow. I don't really like the idea of maintaining two separate workflows that run on two different environments (that could break in 2*n different ways 🙃).

**Comment by nickmeinhold** [comment]
Well said @Jei! I'm pretty sure @tourdownunder would be happy for us to go ahead and remove the android workflow in #107. We can always add it back anyway.

**Comment by Jei** [comment]
Closed by #107
