### ISSUE TITLE
Shouldn't need a timer to scroll to most recent

### ISSUE THREAD

**Issue by gaslitbytech** [adventuresin/chat_app#129]
Solution to #125  isn't ideal as it timer and is clumsy. 

Tried to use https://www.didierboelens.com/2019/04/addpostframecallback/ though had error simular to https://github.com/flutter/flutter/issues/33648

**Comment by nickmeinhold** [comment]
Doing some searching, the problem of scrolling to an offset in a flutter listview is (surprisingly I thought) still an unsolved issue:

[Provide method and/or config to programmatically scroll to ListView index · Issue #12319 · flutter/flutter](https://github.com/flutter/flutter/issues/12319)
