### ISSUE TITLE
When creating a new message, we call toDate() on null

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#139]
In `document_snapshot_extensions.dart`, at: 
```
timestamp: (data['timestamp'] as Timestamp).toDate(),
```

**Comment by gaslitbytech** [comment]
In python I would use a ternary operator or inline if statement much like [this](https://stackoverflow.com/a/58027593/567606). It seems dart has a need equivalent with `??`

`timestamp: ((data['timestamp'] as Timestamp) ?? Timestamp.now()).toDate(),`

**Comment by nickmeinhold** [comment]
I think that's a good solution!  [Conditional expressions](https://dart.dev/guides/language/language-tour#conditional-expressions) are a really powerful tool imo, especially in this declarative world of flutter!
