### ISSUE TITLE
Conversations Page throws RangeError when a new conversation is created

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#146]
RangeError (RangeError (index): Invalid value: Not in range 0..`X`, inclusive: `(X+1)`) 

Thrown in ConversationsViewModel -> getListTile

**Comment by nickmeinhold** [comment]
@tourdownunder do you have any interest in looking into this bug?  I ask because it's somewhat related to the tests you've done (in that it's in the ConversationsPage). We know it's probably not in the view model itself now (thanks to your tests) but I thought it might be a natural extension of what you've been doing to do some widget tests of the ConversationsPage. 

I've been looking at this and thinking of doing some widget tests (and/or integration tests with the local emulator) and I'm more than happy to do it, just thought it may be of interest?

**Comment by gaslitbytech** [comment]
Sure @nickmeinhold. I’ll take a look
