### ISSUE TITLE
Add a github actions workflow for building Android app

### ISSUE THREAD

**Issue by adventuresin** [adventuresin/chat_app#16]
review examples, eg: 
https://github.com/adam7/fructikav2/blob/master/.github/workflows/build-and-test.yml 

- [ ] should we (can we) just use the Mac workflow to build and deploy for Android as well? 
- [ ] need to download google-services.json to correct place in project

**Comment by nickmeinhold** [comment]
@Jei is this done?  I saw the Android workflow ran through successfully on your last merge - nice work, thanks mate!

**Comment by Jei** [comment]
It's done. Sorry, I forgot to close the issue. Thank you!
