### ISSUE TITLE
Add a github actions workflow for deploying iOS app

### ISSUE THREAD

**Issue by adventuresin** [adventuresin/chat_app#17]
## Firebase App Distribution 

With Fastlane 
- [Distribute iOS apps to testers using fastlane  |  Firebase](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane)
- [Distribute Android apps to testers using fastlane  |  Firebase](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane) 

There is an action that lets you use the firebase cli 
[w9jds/firebase-action: GitHub Action for interacting with Firebase](https://github.com/w9jds/firebase-action) 

## .app -> .ipa 

"On iOS an extra build is required since flutter build builds an .app rather than archiving .ipas for release." 
https://flutter.dev/docs/deployment/cd

[How to convert .app to .ipa](https://stackoverflow.com/a/49478854/1992736)

## App Signing 

One option is to put credentials in google cloud storage and use fastlane match: 

see: [fastlane docs > match > google cloud storage](https://docs.fastlane.tools/actions/match/#google-cloud-storage) 

This is briefly described in [First look: Using GitHub actions for building iOS and Android apps](https://medium.com/@jonnyburger/first-look-using-github-actions-for-building-ios-and-android-apps-4749609b96f0)

[fastlane docs](https://docs.fastlane.tools/) 

There are a few fastlane actions, this looks like the best:
[maierj/fastlane-action: A GitHub action for executing fastlane lanes.](https://github.com/maierj/fastlane-action) 

Combine fastlane with Firebase App Distribution? 
[Distribute iOS apps to testers using fastlane  |  Firebase](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane) 

Notes: 
- I couldn't seem to create an App Identifier on the Apple Dev Console with our existing bundle id (just kept getting an error message with nothing helpful, just "error" essentially) 
- all the App Identifiers I had there started with co.enspyr (which is the same as the email for the main account - contact@enspyr.co) 
- So my question is: to deploy to iTunesConnect (or whatever it is now) it seems we'll need to use a bundle identifier that starts with co.enspyr... does that sound reasonable to you guys? @tourdownunder @Jei 
- If so, it will mean creating new apps on the Firebase console but I think the only thing that we would need to change is to use the new firebase config files (which we have to do at some stage anyway because I accidentally committed them a while back) 
- Just sanity checking really, happy to be corrected though! 
- EDIT: looking again, I do have app identifiers that don't start with co.enpsyr so it's not that.  Reading [this](https://stackoverflow.com/questions/20565565/an-app-id-with-identifier-is-not-available-please-enter-a-different-string) made me think maybe the app identifier is already 'used' because another member of the group originally created the app that got pushed up the central repository and maybe their XCode had created the app identifier automatically?  The same solution should apply anyway.

**Comment by nickmeinhold** [comment]
The CI is up and running, the CD will be added in #19.  This issue has some old notes that are no longer relevant.
