### ISSUE TITLE
Don't repeat date in each message

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#172]
Instead of including the full date in each message, we could (potentially) group the messages by date under a header and just have the time for each date.  There are lots of ways we could do it, some options are: 

Whatsapp has a floating date item centred horizontally at top of the messages list: 
![whatsapp-desktop-0-2-2243-now-available-for-download-509568-2.jpg (1214×807)](https://news-cdn.softpedia.com/images/news2/whatsapp-desktop-0-2-2243-now-available-for-download-509568-2.jpg)

Messenger puts a date item in the messages list, once per day (when there were messages on that day) 
![Snimok-e`krana-2015-04-09-v-13.23.58-640x371.png (640×371)](http://droider.ru/wp-content/uploads/2015/04/Snimok-e%60krana-2015-04-09-v-13.23.58-640x371.png)

Signal adds a date item but also has the date on the message bubble (couldn't find a good photo sorry)
![download-mobile-bdc14a52a345c02611f4a8ac2a2796dfd4f5f2d9cf9abbf2494bd3e244d63035.png (708×512)](https://signal.org/assets/screenshots/download-mobile-bdc14a52a345c02611f4a8ac2a2796dfd4f5f2d9cf9abbf2494bd3e244d63035.png)

Slack uses a floating date item and a date item in the list of messages:
![Dark-Mode-Transparent-En.png (2256×1464)](https://slackhq.com/wp-content/uploads/2019/09/Dark-Mode-Transparent-En.png)
- when the floating date item hits the date item in the list, the floating item becomes the next date, something like a [sticky_header](https://pub.dev/packages/sticky_headers)

**Comment by gaslitbytech** [comment]
When I was looking into this a few weeks ago I found [cookbook mixed-list](https://flutter.dev/docs/cookbook/lists/mixed-list) that seems neat to add this sort of feature.
