### ISSUE TITLE
Create a privacy policy

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#20]
The [Facebook App](https://developers.facebook.com/apps/219671022403094/dashboard/) we use for facebook auth requires a Privacy Policy Url before you can set status to Live. 

Currently the Privacy Policy Url is set to this issue.  

Here's a quick temporary solution that's a bit better: 
https://stackoverflow.com/a/48134670/1992736

**Comment by tourdownunder** [comment]
@Jei found this that is prefect https://app-privacy-policy-generator.firebaseapp.com/

**Comment by nickmeinhold** [comment]
@Jei did you generate the privacy policy?  I'm happy to work on the hosting part unless someone else wants to do it?

**Comment by Jei** [comment]
I've just generated a privacy policy, you can find it in the shared Google Drive folder of the project, under "privacy policy".

**Comment by nickmeinhold** [comment]
Brilliant! This is done then (please reopen if I'm jumping the gun)
