### ISSUE TITLE
Add unit tests for DateTime extensions

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#201]
#200 added extensions on DateTime that we haven't added tests for yet. 

- [x] isSameDate 
- [x] printDate

**Comment by gaslitbytech** [comment]
I have a draft of tests for `isSameDate` in branch feature/add-tests-date-time-extension-issue-201

One interesting thing is do we want to be able to compare with null? I believe it is worth it and that we should change the implementation to return false if other is null.

```dart
    test('.isSameDate() returns False when compared to null', () {
      var t0 = DateTime.parse('1969-07-20 20:18:04');
      DateTime t1;

      expect(false, t0.isSameDate(t1));
    }, skip: true);
```

I've found the skip flag which is useful so we can `skip` the test for now until we change functionality. `skip` will allow for better TDD testing before implementing.
