### ISSUE TITLE
stream already been listened to when user clicked on their second conversation

### ISSUE THREAD

**Issue by gaslitbytech** [adventuresin/chat_app#205]
This was that I was not able to click another conversation once I clicked into the first. I instinctively started to think it was the _controller being reused for all conversations.

<img width="912" alt="Screen Shot 2020-07-05 at 5 58 29 pm" src="https://user-images.githubusercontent.com/829044/86528206-2d9ad280-bee9-11ea-9652-c46687ca92ca.png">

**Comment by nickmeinhold** [comment]
Hey mate, thanks for this!  I reckon this calls for a discussion about our "stream management" approach, not sure whether to do that here or in the PR or a separate issue... do you have a preference? 

Just off the to of my head, a couple of points for discussion: 
- I am wondering if your approach to fixing this bug will still produce the error if the user listens to the same conversation twice?  (eg. by selecting a conversation, returning to the conversations page and selecting the same conversation again) 
- would it be simpler to to use a broadcast stream (with `.asBroadcastStream()`) which doesn't throw the error when the stream is listened to more than once?  (this is just off the top of my head and may be a bad approach)

**Comment by gaslitbytech** [comment]
I'll start with the second point. Broadcast Stream is not a fix for this scenario. My mental model is television stations and that every unique conversation is a TV station. I don't think it is correct to reuse the same controller as its jumbling the signal. The idea to use a map is to keep it seperate which seems to behave as expected in my manual testing.

As to your first point I believe the above addresses it, though I'll be honest I don't pretend to know exactly why.

**Comment by gaslitbytech** [comment]
Reopened the issue to acknowledge that though PR #204 is merged this discussion isn't finished.

**Comment by nickmeinhold** [comment]
Thanks mate, I made #209 - thought a separate issue would be good to discuss in, I'll close this one again but re-open if you want to of course

**Comment by nickmeinhold** [comment]
Re-opening to put a PR up
