### ISSUE TITLE
Set buckets to correct permissions 

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#231]
- [x] config bucket to allow download
- [x] credentials bucket to not visible 

See: 
- [Storage browser – Storage – adventures-in-chat – Google Cloud Platform](https://console.cloud.google.com/storage/browser?forceOnBucketsSortingFiltering=false&authuser=0&project=adventures-in-chat&prefix=) 
- [adventures-in-chat – Storage – Firebase console](https://console.firebase.google.com/u/0/project/adventures-in-chat/storage/config-adventures-in-chat/files~2F)

**Comment by nickmeinhold** [comment]
@tamari-gray when you get a sec would you mind checking what you see when you go to: [adventures-in-chat – Storage – Firebase console](https://console.firebase.google.com/u/0/project/adventures-in-chat/storage/config-adventures-in-chat/files~2F)

I see: 
<img width="896" alt="Screen Shot 2020-08-27 at 1 51 09 am" src="https://user-images.githubusercontent.com/1059276/91327163-86f7f180-e808-11ea-87b2-fdf01d0fb96d.png">

I'm hoping you don't see the credentials bucket? 

EDIT: actually it's fine if you can see it, I just want to have it set that we can't download anything - I think I have it setup that way, if you could see if you can download from the bucket that'd be awesome... thanks!

**Comment by nickmeinhold** [comment]
@tamari-gray friendly ping :-) did you check this?

**Comment by tamari-gray** [comment]
No I didn't! I'll have a check tonight 😁

**Comment by nickmeinhold** [comment]
Awesome thanks! 🙂

**Comment by tamari-gray** [comment]
only coming up with an error, still shows if i refresh the page

![firease-nick](https://user-images.githubusercontent.com/49229277/92474690-9ec77080-f21f-11ea-8813-e17aa94f959c.PNG)

**Comment by nickmeinhold** [comment]
Perfect!  Thanks for that @tamari-gray!
