### ISSUE TITLE
Create a new Facebook app and update project config for Facebook sign in

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#28]
I did originally create a new Facebook app specifically for the chat app but somewhere along the line I realised the config details (app id, etc.) we were using was from an old Facebook app of mine called Good Food and the Facebook app I created had disappeared.  Bit of a weird mystery.  

Anyway we just need to: 
- [x] create a new Facebook app, called something like "Adventures In Chat App" 
- [x] update the config setting in the Firebase console 
- [x] update the Facebook app config settings (eg. whitelisted Urls, etc.)

**Comment by tourdownunder** [comment]
![IMG_0772](https://user-images.githubusercontent.com/829044/75140288-ac654f00-5742-11ea-8c39-2bce77aeef38.PNG)

I got this after logging out of facebook and logging back in again. 

It was on branch fix-pods-issue

**Comment by nickmeinhold** [comment]
Thanks mate!  

I'm pretty sure the fix here will be to delete the app from the device and run it again (so it can reinstall).  If I'm right it's because the device is still 'signed in' with the Facebook SDK (with credentials from the old facebook app).  

Sorry for the stuff around! 

Our sign out feature currently doesn't sign out with facebook (or google) but we have #25 for that (but you probably know that already).

**Comment by tourdownunder** [comment]
It was fine after removing the app first
