### ISSUE TITLE
Fix fatal error: module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#39]
This is happening during CI 

eg: https://github.com/adventuresin/chat_app/runs/463824329?check_suite_focus=true

Initially I thought it was due to the missing firebase config files but the CI now downloads the files before running the build so unless there's something weird going on in CI, the error is due to something else. 

This issue looks like the same thing: https://github.com/FirebaseExtended/flutterfire/issues/1243 

Doing some searching, I think we should try:  
- [ ] upgrading dependencies (both dart packages and underlying pods)

**Comment by nickmeinhold** [comment]
I am able to repro this locally by running `flutter build ios --release --no-codesign`

**Comment by Khalimovs** [comment]
In flutter app you can do following: 
1. Delete **Podfile** and **Podfile.lock** from ios folder
2. Run **flutter clean** on your project root folder
3. Check **pubspec.yaml** file if  **cloud_firestore: ^0.13.3** is included
4. Build app -> flutter automatically generates a **Podfile** (building the app may take some time as it downloads required files from internet)

**Comment by nickmeinhold** [comment]
Thanks for the help @Khalimovs!  

In our case it seems a change to the Podfile, having the platform set to ios11, ie. with `platform :ios, '11.0'` was to blame. 

Commenting it out seems to have fixed the problem.  

Appreciate you taking the time to try and help!
