### ISSUE TITLE
Add User Search Page

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#43]
![user search page](https://user-images.githubusercontent.com/1059276/75153399-71254900-575f-11ea-8b23-9d34554e33b7.png)

We need to get the users section of firestore setup properly: 
- [ ] firestore security rules: all users can view, only user can write? 
- [ ] get entries for everyone in `/users` - anyone who signed in before the cloud function went live will need to [delete their firebase account](https://console.firebase.google.com/project/adventures-in/authentication/users) then sign out and back in again 
  - [ ] @tourdownunder 
  - [x] @Jei 
  - if I'm not making sense don't worry about it, we can do this when we meet up next 
  - I can delete your account if you're happy for me to, it doesn't mean anything at this point other than needing to link accounts again, I just didn't want to assume

**Comment by Jei** [comment]
> firestore security rules: everyone can view, only user can write?

Does that "everyone" mean non-users?

> anyone who signed in before the cloud function went live will need to delete their firebase account then sign out and back in again

I deleted my account and signed in again. 👍

**Comment by nickmeinhold** [comment]
Thanks for the clarification @Jei - I meant all users.

**Comment by nickmeinhold** [comment]
This was done in #53
