### ISSUE TITLE
Decide on using Material for both platforms or Cupertino for iOS

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#45]
@Jei when you were talking about this today, the package I was trying to remember the name of is `flutter_platform_widgets`
- [Platform-Aware Widgets in Flutter | raywenderlich.com](https://www.raywenderlich.com/4968762-platform-aware-widgets-in-flutter) 

Did we land anywhere by the end of the discussion?  

Personally my opinion for my own apps is that the best result comes from customising Material to the point where the app doesn't really look particularly Androidy or iOSy but has an interesting, unique look and feel and use that for both platforms.  But as I was saying today I've never done the Cupertino for iOS and Material for Android thing so I'm interested in learning about it.  Basically my vote is I abstain as I don't mind either way.

**Comment by Jei** [comment]
> @Jei when you were talking about this today, the package I was trying to remember the name of is `flutter_platform_widgets`
> 
> * [Platform-Aware Widgets in Flutter | raywenderlich.com](https://www.raywenderlich.com/4968762-platform-aware-widgets-in-flutter)
> 

Thank you! I'll check it out.

> Did we land anywhere by the end of the discussion?
> 
> Personally my opinion for my own apps is that the best result comes from customising Material to the point where the app doesn't really look particularly Androidy or iOSy but has an interesting, unique look and feel and use that for both platforms. But as I was saying today I've never done the Cupertino for iOS and Material for Android thing so I'm interested in learning about it. Basically my vote is I abstain as I don't mind either way.

We didn't reach a conclusion. I'm personally more familiar with Material design, but I don't think it always translates well on iOS. I think we could use that "flutter_platform_widgets" plugin for most of the UI components, at least for the first version of the app, and then see if we can improve or customize them later.

**Comment by nickmeinhold** [comment]
further discussion in #52
