### ISSUE TITLE
Change app name

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#46]
When we originally created the project one of us just picked a random name and now I'm not sure it makes sense.  The app name is meetup_chatapp.  

My suggestion (just to start off discussion) is to change it to adventures_in_chat with the display name being Adventures In Chat (or maybe just Adventures In?).  

Any other suggestions?  Or if you think it's not worth worrying about please add that feedback. 

This reddit post has some relevant resources if we do decide to change the name: 
[Change app display name during production : FlutterDev](https://www.reddit.com/r/FlutterDev/comments/f9lvom/change_app_display_name_during_production/?utm_source=ifttt)

**Comment by Jei** [comment]
Naming things is always the hardest part of software development 😂
I vote for "Adventures In". Alternatively, I propose "Flat" (as in "FLutter chAT").
