### ISSUE TITLE
Add the time sent to each chat message

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#78]
@Jei I couldn't find the discussion I was telling you about but I found this brief comparison that might be useful if you haven't seen it yet:
https://github.com/flutter/flutter/issues/31523#issuecomment-488500982

**Comment by tourdownunder** [comment]
After seeing the data structure of https://github.com/adventuresin/chat_app/wiki/Backend-Design#messages this should be simple to add timestamp if we neglect timezone.

**Comment by nickmeinhold** [comment]
Check out [timezone | Dart Package](https://pub.dev/packages/timezone)
