### ISSUE TITLE
Virtual Keyboard hiding message text in chat page

### ISSUE THREAD

**Issue by tourdownunder** [adventuresin/chat_app#79]
Following reproduced on iphone 6s. 

`chat_page.dart` shows as the user is typing they can not see the contents of the message as its hidden by the `virtual keyboard`

I'm going to attempt to solve this immediately.

**Comment by tourdownunder** [comment]
This article seems like a possible solution

https://medium.com/flutter-nyc/avoiding-the-on-screen-keyboard-in-flutter-ae0e46ecb96c

**Comment by nickmeinhold** [comment]
https://stackoverflow.com/a/53800595/1992736
