### ISSUE TITLE
Issue with iphone 6s iOS 13.3.1

### ISSUE THREAD

**Issue by tourdownunder** [adventuresin/chat_app#8]
The issue I've been battling today using my iPhone 6s updated earlier this week to iOS 13.3.1. Seems to be related to https://github.com/flutter/flutter/issues/45306

```text
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/AF85BF16-2E06-42D1-8696-2F07B2D0CFE3/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/AF85BF16-2E06-42D1-8696-2F07B2D0CFE3/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/AF85BF16-2E06-42D1-8696-2F07B2D0CFE3/Runner.app/Frameworks/Flutter.framework/Flutter'

	/private/var/containers/Bundle/Application/AF85BF16-2E06-42D1-8696-2F07B2D0CFE3/Runner.app/Frameworks/Flutter.framework/Flutter: stat() failed with errno=25
Message from debugger: Terminated due to signal 6
```

This issue is with all other iOS apps such as one on flutter_vignettes as well

**Comment by nickmeinhold** [comment]
Your idea today of using the "Company / Organization" provisioning profile rather than the Personal Team one apparently would solve the problem (see [here](https://github.com/flutter/flutter/issues/49504)).

**Comment by tourdownunder** [comment]
Hi @nickmeinhold 

I attempted use the Company / Organiszation profile though it seemed there was a issue with caching on xcode as it insisted that my email only had a Personal Team. Is it worth trying to use a different email that doesn't have a Personal Team and perhaps xcode wouldn't be confused. I'll PM you a email.

**Comment by tourdownunder** [comment]
The solution of using your Company / Organisation profile worked.

**Comment by tourdownunder** [comment]
The solution of using your Company / Organisation profile worked.
