### ISSUE TITLE
Setup a gitflow workflow with status checks on PRs

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#98]
We discussed this today (02 May 20) and agreed to go ahead.  The issue is in case there are any misunderstandings on what was agreed, to record what we are doing and for project management. 

- [x] create a dev branch and add the merge restriction 
- [x] add status checks to PRs 
- [x] update the [Contributing · Wiki](https://github.com/adventuresin/chat_app/wiki/Contributing) 

References: 
- [Gitflow Workflow | Atlassian Git Tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by nickmeinhold** [comment]
@Jei and @tourdownunder what do you think about making `dev` the default branch?  The only difference I know of is that it saves time as you don't have to change `master` to `dev` when creating a PR.  


My thinking is based in the description here: [Setting the default branch - GitHub Help](https://help.github.com/en/github/administering-a-repository/setting-the-default-branch)

**Comment by nickmeinhold** [comment]
I went ahead and made `dev` the default  branch while I was changing the restrictions on `dev` and `master`.  The option was right in front of me and I figured it's easy to change back if we want.

**Comment by Jei** [comment]
I agree that in our case it's easier to have the `dev` branch as the default one. I also think it's nicer this way since the project is still in the development stage.

**Comment by nickmeinhold** [comment]
Thanks for the feedback!
